"""Add LocalPost model

Revision ID: 5f97ed2f91d3
Revises: a82b38db16bd
Create Date: 2026-03-02 07:56:22.089459

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f97ed2f91d3'
down_revision = 'a82b38db16bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localpost',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('google_post_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('topic_type', sa.Enum('STANDARD', 'EVENT', 'OFFER', 'ALERT', name='topictype'), nullable=False),
    sa.Column('state', sa.Enum('UNSPECIFIED', 'REJECTED', 'LIVE', 'PROCESSING', name='poststate'), nullable=False),
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alert_type', sa.Enum('COVID_19', name='alerttype'), nullable=True),
    sa.Column('event_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('event_start_time', sa.DateTime(), nullable=True),
    sa.Column('event_end_time', sa.DateTime(), nullable=True),
    sa.Column('offer_coupon', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('offer_redeem_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('offer_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cta_action_type', sa.Enum('BOOK', 'ORDER', 'SHOP', 'LEARN_MORE', 'SIGN_UP', 'CALL', name='actiontype'), nullable=True),
    sa.Column('cta_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_post_name')
    )
    op.create_index(op.f('ix_localpost_location_id'), 'localpost', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localpost_location_id'), table_name='localpost')
    op.drop_table('localpost')
    # ### end Alembic commands ###
