"""Add ProfileCompletionScore model

Revision ID: 6822ef53332c
Revises: 5f97ed2f91d3
Create Date: 2026-03-02 07:59:42.647853

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6822ef53332c'
down_revision = '5f97ed2f91d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profilecompletionscore',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('achieved_points', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=False),
    sa.Column('missing_criteria', sa.JSON(), nullable=True),
    sa.Column('completed_criteria', sa.JSON(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profilecompletionscore_location_id'), 'profilecompletionscore', ['location_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profilecompletionscore_location_id'), table_name='profilecompletionscore')
    op.drop_table('profilecompletionscore')
    # ### end Alembic commands ###
