"""Add SyncRecord model

Revision ID: a82b38db16bd
Revises: fe56fa70289e
Create Date: 2026-03-02 07:54:47.211139

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a82b38db16bd'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syncrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('REVIEWS', 'POSTS', 'LOCATIONS', 'MEDIA', 'QA', 'PERFORMANCE', name='resourcetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('items_synced', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncrecord_location_id'), 'syncrecord', ['location_id'], unique=False)
    op.create_index(op.f('ix_syncrecord_restaurant_id'), 'syncrecord', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncrecord_restaurant_id'), table_name='syncrecord')
    op.drop_index(op.f('ix_syncrecord_location_id'), table_name='syncrecord')
    op.drop_table('syncrecord')
    # ### end Alembic commands ###
